version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      # Add other environment variables as needed
      # - GITHUB_TOKEN=your_github_token
      # - TWITTER_BEARER_TOKEN=your_twitter_token
      # - SENDGRID_API_KEY=your_sendgrid_key
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always